apiVersion: batch/v1
kind: Job
metadata:
  name: oscap
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 600
  backoffLimit: 2
  template:
    metadata:
      name: oscap
    spec:
      containers:
      - name: oscap
        image: docker.io/ekolesni/openscap-ocp4
        command: ["oscap-chroot", "/host", "--verbose", "DEVEL", "xccdf", "eval", "--fetch-remote-resources", "--profile", "xccdf_org.ssgproject.content_profile_ospp",  "--report", "/tmp/report.html", "/var/lib/content/ssg-rhel7-ds-1.3.xml"]
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /host
          name: host
      hostNetwork: true
      hostPID: true
#      nodeName: ip-10-0-128-123.ec2.internal
      restartPolicy: Never
      volumes:
      - hostPath:
        path: /
        type: Directory
        name: host

